package horarios.vista;

import horarios.controlador.LoginController;
import horarios.util.SoundManager;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * ============================================================
 *  VISTA: LoginWindow
 *  CAPA:  Vista (MVC)
 * ============================================================
 *  Primera ventana del sistema: permite al director
 *  autenticarse o ir al registro de nueva cuenta.
 *
 *  Flujo de uso:
 *    1. Usuario escribe username + password y presiona "Iniciar sesion"
 *       (o tecla Enter desde cualquier campo).
 *    2. Se llama a LoginController.iniciarSesion() para validar.
 *    3. Si es correcto -> abre MainWindow y cierra esta ventana.
 *    4. Si es incorrecto -> muestra mensaje de error.
 *    5. El boton "Registrarse" abre RegisterWindow.
 *
 *  Usa LoginController como intermediario; jamas llama
 *  directamente al DAO ni a la base de datos.
 * ============================================================
 */
public class LoginWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginWindow.class.getName());
    
    // ── Instancia de tu controlador ───────────────────────────────────────────
    private final LoginController controller = new LoginController();

    /**
     * Creates new form LoginVista
     */
    public LoginWindow() {
        initComponents();
        initCustomListeners();
    }

    /**
     * Configuramos las acciones de los "botones" (JLabels) y la tecla Enter.
     */
    private void initCustomListeners() {
        FieldUsuario.setText("");
        FieldContraseña.setText("");

        jLabelBtnIniciarSesion.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                intentarLogin();
            }
        });

        jLabelBtnRegistrarse.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                abrirRegistro();
            }
        });

        MouseAdapter salirAction = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.exit(0);
            }
        };
        jLabelBtnSalir.addMouseListener(salirAction);
        jLabelBtnCerrarVentana.addMouseListener(salirAction);

        KeyAdapter enterAction = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    intentarLogin();
                }
            }
        };
        FieldUsuario.addKeyListener(enterAction);
        FieldContraseña.addKeyListener(enterAction);
    }

    private void intentarLogin() {
        String usuario      = FieldUsuario.getText().trim();
        String contrasena   = FieldContraseña.getText().trim(); 

        if (usuario.isEmpty() || contrasena.isEmpty()) {
            mostrarMensaje("Todos los campos son obligatorios", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        new Thread(() -> {
            boolean ok = controller.iniciarSesion(usuario, contrasena);
            SwingUtilities.invokeLater(() -> {
                if (ok) {
                    SoundManager.playSuccess();
                    mostrarMensaje("¡Inicio de sesión exitoso!", JOptionPane.INFORMATION_MESSAGE);
                    dispose(); // Cerramos el login
                    new MainWindow(usuario, 0).setVisible(true); // Abrimos tu menú principal
                } else {
                    SoundManager.playError();
                    mostrarMensaje("Credenciales incorrectas. Verifique usuario y contraseña.", JOptionPane.ERROR_MESSAGE);
                }
            });
        }).start();
    }

    private void abrirRegistro() {
        dispose();
        new RegisterWindow().setVisible(true);
    }

    private void mostrarMensaje(String texto, int tipoMensaje) {
        JOptionPane.showMessageDialog(this, texto, "Aviso del Sistema", tipoMensaje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBtnCerrarVentana = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FieldUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelBtnIniciarSesion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelBtnRegistrarse = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelBtnSalir = new javax.swing.JLabel();
        FieldContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(100, 0, 25));

        jPanel3.setBackground(new java.awt.Color(204, 160, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INICIO DE SESIÓN");

        jLabelBtnCerrarVentana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnCerrarVentana.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnCerrarVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnCerrarVentana.setText("X");
        jLabelBtnCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addContainerGap(322, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelBtnCerrarVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        Bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 120));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 0, 25));
        jLabel3.setText("Usuario:");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        FieldUsuario.setText("jTextField1");
        FieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsuarioActionPerformed(evt);
            }
        });
        Bg.add(FieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 340, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 0, 25));
        jLabel4.setText("Contraseña:");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        jLabelBtnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnIniciarSesion.setForeground(new java.awt.Color(204, 160, 0));
        jLabelBtnIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnIniciarSesion.setText("INICIAR SESIÓN");
        jLabelBtnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, 40));

        jPanel5.setBackground(new java.awt.Color(204, 204, 0));

        jLabelBtnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnRegistrarse.setText("REGISTRARME");
        jLabelBtnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Bg.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 0, 0));

        jLabelBtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnSalir.setText("SALIR");
        jLabelBtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        FieldContraseña.setText("jPasswordField1");
        Bg.add(FieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsuarioActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JPasswordField FieldContraseña;
    private javax.swing.JTextField FieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBtnCerrarVentana;
    private javax.swing.JLabel jLabelBtnIniciarSesion;
    private javax.swing.JLabel jLabelBtnRegistrarse;
    private javax.swing.JLabel jLabelBtnSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
