package horarios.vista;

import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * ============================================================
 *  VISTA: MainWindow
 *  CAPA:  Vista (MVC)
 * ============================================================
 *  Menu principal del sistema, visible tras iniciar sesion.
 *  Muestra el nombre del usuario activo, la fecha actual,
 *  y botones de acceso a cada modulo del sistema:
 *    - Gestion de Profesores  -> ProfesoresWindow
 *    - Gestion de Materias    -> MateriasWindow
 *    - Gestion de Grupos      -> GruposWindow
 *    - Gestion de Especialidades -> EspecialidadesWindow
 *    - Modulo de Horarios     -> HorariosWindow
 *
 *  Recibe el username y el userId del director autenticado
 *  (provistos por LoginWindow al hacer login exitoso).
 *  El userId se pasa a cada subventana para trazar acciones
 *  del usuario en la BD (auditoria).
 *
 *  No tiene controlador propio: su unica logica es abrir
 *  ventanas y mostrar la fecha/hora, lo cual no requiere
 *  acceso a datos ni validaciones de negocio.
 * ============================================================
 */
public class MainWindow extends javax.swing.JFrame {
    
    private final String username;
    private final int userId;

    public MainWindow(String username, int userId) {
        this.username = username;
        this.userId = userId;
        
        initComponents();
        initCustomListeners();
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public MainWindow() {
        this.username = "admin";
        this.userId = 1;
        initComponents();
        initCustomListeners();
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void initCustomListeners() {
        jLabel2.setText("USUARIO: " + username);
        String fecha = new SimpleDateFormat("dd 'de' MMMM yyyy  -  HH:mm").format(new Date());
        jLabel3.setText("FECHA Y HORA: " + fecha);

        jLabelBtnGestionProfesores.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                new ProfesoresWindow(MainWindow.this, userId).setVisible(true);
            }
        });

        jLabelBtnGestionDeMaterias.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                new MateriasWindow(MainWindow.this, userId).setVisible(true);
            }
        });

        jLabelBtnGestionDeGrupos.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                new GruposWindow(MainWindow.this, userId).setVisible(true);
            }
        });

        jLabelBtnGestionDeEspecialidades.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                new EspecialidadesWindow(MainWindow.this, userId).setVisible(true);
            }
        });

        jLabelBtnModuloDeHorarios.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                try {
                    new HorariosWindow(userId, MainWindow.this).setVisible(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(MainWindow.this, "Error: " + ex.getMessage());
                }
            }
        });

        jLabelBtnSalirDelSistema.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                int r = JOptionPane.showConfirmDialog(MainWindow.this, 
                        "¿Está seguro que desea salir del sistema?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
                if (r == JOptionPane.YES_OPTION) System.exit(0);
            }
        });
    }
    /**
     * Creates new form MenuVista
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelBtnGestionProfesores = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelBtnGestionDeMaterias = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelBtnGestionDeGrupos = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelBtnGestionDeEspecialidades = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelBtnModuloDeHorarios = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelBtnSalirDelSistema = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 160, 0));
        jLabel1.setText("GENERADOR DE HORARIOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 160, 0));
        jLabel2.setText("USUARIO:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FECHA Y HORA:");

        jPanel2.setBackground(new java.awt.Color(204, 160, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(596, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 70));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        jLabelBtnGestionProfesores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnGestionProfesores.setForeground(new java.awt.Color(204, 160, 0));
        jLabelBtnGestionProfesores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnGestionProfesores.setText("GESTIÓN DE PROFESORES");
        jLabelBtnGestionProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        Bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 90));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        jLabelBtnGestionDeMaterias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnGestionDeMaterias.setForeground(new java.awt.Color(204, 160, 0));
        jLabelBtnGestionDeMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnGestionDeMaterias.setText("GESTIÓN DE MATERIAS");
        jLabelBtnGestionDeMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionDeMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionDeMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        Bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));

        jLabelBtnGestionDeGrupos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnGestionDeGrupos.setForeground(new java.awt.Color(204, 160, 0));
        jLabelBtnGestionDeGrupos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnGestionDeGrupos.setText("GESTIÓN DE GRUPOS");
        jLabelBtnGestionDeGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionDeGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionDeGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        Bg.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));

        jLabelBtnGestionDeEspecialidades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnGestionDeEspecialidades.setForeground(new java.awt.Color(204, 160, 0));
        jLabelBtnGestionDeEspecialidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnGestionDeEspecialidades.setText("GESTIÓN DE ESPECIALIDADES");
        jLabelBtnGestionDeEspecialidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionDeEspecialidades, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnGestionDeEspecialidades, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        Bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 153, 0));

        jLabelBtnModuloDeHorarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnModuloDeHorarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnModuloDeHorarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnModuloDeHorarios.setText("MÓDULO DE HORARIOS");
        jLabelBtnModuloDeHorarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnModuloDeHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnModuloDeHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        Bg.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 90));

        jPanel8.setBackground(new java.awt.Color(51, 0, 0));

        jLabelBtnSalirDelSistema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnSalirDelSistema.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnSalirDelSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnSalirDelSistema.setText("SALIR DEL SISTEMA");
        jLabelBtnSalirDelSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnSalirDelSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnSalirDelSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        Bg.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204, 160, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(590, 4));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        Bg.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 590, 4));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("SISTEMA DE GESTION DE HORARIOS-CBTIS");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("SELECCIONE UNA OPCIÓN");
        Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MainWindow("admin", 1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBtnGestionDeEspecialidades;
    private javax.swing.JLabel jLabelBtnGestionDeGrupos;
    private javax.swing.JLabel jLabelBtnGestionDeMaterias;
    private javax.swing.JLabel jLabelBtnGestionProfesores;
    private javax.swing.JLabel jLabelBtnModuloDeHorarios;
    private javax.swing.JLabel jLabelBtnSalirDelSistema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
