/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package horarios.vista;
import horarios.controlador.LoginController;
import horarios.util.SoundManager;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author axelp
 */
public class RegisterWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterWindow.class.getName());

    /**
     * Creates new form LoginVista
     */
    private final LoginController controller = new LoginController();

    public RegisterWindow() {
        initComponents();
        initCustomListeners();
        setLocationRelativeTo(null);
    }

    private void initCustomListeners() {
        FieldUsuario.setText("");
        FieldCorreo.setText("");
        FieldContraseña.setText("");
        FieldConfirmarContraseña.setText("");
        FieldClave.setText("");

        jLabelBtnRegistrarUsuario.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                registrarUsuario();
            }
        });

        jLabelBtnRegresarLobby.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                abrirLogin();
            }
        });

        jLabelBtnCerrarVentana.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                System.exit(0);
            }
        });

        KeyAdapter enterAction = new KeyAdapter() {
            @Override public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    registrarUsuario();
                }
            }
        };
        FieldUsuario.addKeyListener(enterAction);
        FieldCorreo.addKeyListener(enterAction);
        FieldContraseña.addKeyListener(enterAction);
        FieldConfirmarContraseña.addKeyListener(enterAction);
        FieldClave.addKeyListener(enterAction);
    }

    private void registrarUsuario() {
        String username = FieldUsuario.getText().trim();
        String email = FieldCorreo.getText().trim();
        String password = FieldContraseña.getText().trim();
        String confirmPassword = FieldConfirmarContraseña.getText().trim();
        String claveSistema = FieldClave.getText().trim();

        String error = controller.validarFormularioRegistro(username, email, password, confirmPassword, claveSistema);
        
        if (error != null) {
            JOptionPane.showMessageDialog(this, error, "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (controller.registrar(username, password, email, claveSistema)) {
            SoundManager.playSuccess();
            JOptionPane.showMessageDialog(this, "¡Registro exitoso!\n\nAhora puede iniciar sesión.", "Registro Completado", JOptionPane.INFORMATION_MESSAGE);
            abrirLogin();
        } else {
            SoundManager.playError();
            JOptionPane.showMessageDialog(this, "Error al registrar el usuario.\nEs posible que el nombre de usuario ya exista.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirLogin() {
        dispose();
        new LoginWindow().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBtnCerrarVentana = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FieldCorreo = new javax.swing.JTextField();
        FieldUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelBtnRegresarLobby = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelBtnRegistrarUsuario = new javax.swing.JLabel();
        FieldContraseña = new javax.swing.JPasswordField();
        FieldConfirmarContraseña = new javax.swing.JPasswordField();
        FieldClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 0, 25));

        jPanel2.setBackground(new java.awt.Color(204, 160, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(830, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE USUARIO");

        jLabelBtnCerrarVentana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBtnCerrarVentana.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnCerrarVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnCerrarVentana.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(273, 273, 273))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBtnCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(13, 13, 13))
        );

        Bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 0, 25));
        jLabel2.setText("Clave del sistema:");
        Bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 0, 25));
        jLabel3.setText("Complete los siguientes campos:");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 0, 25));
        jLabel4.setText("Usuario:");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 20));

        FieldCorreo.setText("jTextField1");
        FieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCorreoActionPerformed(evt);
            }
        });
        Bg.add(FieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 380, -1));

        FieldUsuario.setText("jTextField1");
        FieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsuarioActionPerformed(evt);
            }
        });
        Bg.add(FieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 380, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 0, 25));
        jLabel5.setText("Correo electronico:");
        Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(100, 0, 25));
        jLabel6.setText("Contraseña:");
        Bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(100, 0, 25));
        jLabel7.setText("Confirmar contraseña:");
        Bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, 20));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabelBtnRegresarLobby.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelBtnRegresarLobby.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnRegresarLobby.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnRegresarLobby.setText("Regresar al lobby\n");
        jLabelBtnRegresarLobby.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnRegresarLobby, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnRegresarLobby, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 180, 40));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        jLabelBtnRegistrarUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelBtnRegistrarUsuario.setForeground(new java.awt.Color(204, 160, 0));
        jLabelBtnRegistrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnRegistrarUsuario.setText("Registrar usuario");
        jLabelBtnRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, 40));

        FieldContraseña.setText("jPasswordField1");
        Bg.add(FieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 380, -1));

        FieldConfirmarContraseña.setText("jPasswordField1");
        Bg.add(FieldConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 380, -1));

        FieldClave.setText("jPasswordField1");
        Bg.add(FieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsuarioActionPerformed

    private void FieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JPasswordField FieldClave;
    private javax.swing.JPasswordField FieldConfirmarContraseña;
    private javax.swing.JPasswordField FieldContraseña;
    private javax.swing.JTextField FieldCorreo;
    private javax.swing.JTextField FieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBtnCerrarVentana;
    private javax.swing.JLabel jLabelBtnRegistrarUsuario;
    private javax.swing.JLabel jLabelBtnRegresarLobby;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
